# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0002_auto_20171019_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='text',
        ),
    ]
