# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_site', '0003_auto_20171021_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Successes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_first_site.Topic')),
            ],
        ),
    ]
